name: svg_path_parser
description: >
  A Flutter/Dart utility to parse an SVG path into a
  equivalent Path object from dart:ui library.
version: 1.1.2
homepage: https://github.com/masterashu/svg_path_parser
repository: https://github.com/masterashu/svg_path_parser
issue_tracker: https://github.com/masterashu/svg_path_parser/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  string_scanner: ^1.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.5

flutter:
